### ISSUE TITLE
new label "The unarchiver"

### ISSUE THREAD

**Issue by TJakobING** [erikstam/uninstaller#15]
theunarchiver)
      appTitle="The Unarchiver"
      appProcesses+=("The Unarchiver")
      appFiles+=("/Applications/The Unarchiver.app")
      appFiles+=("/Users/$loggedInUser/Library/HTTPStorages/com.macpaw.site.theunarchiver")
      appFiles+=("/Users/$loggedInUser/Library/HTTPStorages/com.macpaw.site.theunarchiver.binarycookies")
      appFiles+=("/Users/$loggedInUser/Library/Preferences/com.macpaw.site.theunarchiver.plist")
      appFiles+=("/Users/$loggedInUser/Library/Saved Application State/com.macpaw.site.theunarchiver.savedState")
      appReceipts+=("cx.c3.theunarchiver")
  ;;

**Comment by macbofh** [comment]
Thanks for the new label. I included it in the latest build
