### ISSUE TITLE
VLC: Missing File

### ISSUE THREAD

**Issue by GrahamWilliams-DMT** [erikstam/uninstaller#5]
Hey! 

Really excited about this project, I can really see it coming in handy! 

It looks like there could be a file missing from the VLC entry. 

`appFiles+=("/Users/$loggedInUser/Library/Saved Application State/org.videolan.vlc.savedState")`

I usually use [App Eraser](https://github.com/davunt/app-eraser) when I'm removing things, as it seems to do a fantastic job of finding files that have been hidden all over the place. Using this, it appears there was a file entry missing from VLC.

![AppEraser_VLC](https://user-images.githubusercontent.com/74202469/209108210-85cea2f2-380a-4746-bc74-269a0a25213e.png)

![Finder_VLC](https://user-images.githubusercontent.com/74202469/209108322-bcd5b596-f56f-400a-a925-575f549be318.png)

I can see that you're working on seperate_labels like Installomator, so I'll create a pull request there against VLC if that's alright?

**Comment by macbofh** [comment]
Thanks for the addition
